In [4]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages (from xgboost) (1.16.2)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 1.3 MB/s eta 0:01:19
   ---------------------------------------- 0.8/101.7 MB 1.0 MB/s eta 0:01:40
   ---------------------------------------- 1.0/101.7 MB 1.2 MB/s eta 0:01:22
    --------------------------------------- 1.3/101.7 MB 1.2 MB/s eta 0:01:24
    --------------------------------------- 1.6/101.7 MB 1.2 MB/s eta 0:01:25
    --------------------------------------- 1.8/101.7 MB 1.2 MB/s eta 0:01:26
    --------------------------------------- 2.1/101.7 MB 1.3 MB/s eta 0:01:20
    --------------------------------------- 2.4/101.7 MB 1.2 MB/s eta 0:01:24
    --------------------------------------- 2.4/101.7 MB 1.2 MB/s eta 0:01:24
   - -------------------------------------- 2.9/101.7 MB 1.2 MB/s eta 0:01:23
   - -------------------------------------- 3.1/101.7 MB 1.2 MB/s eta 0:01:23
   - -------------------------------------- 3.4/101.7 MB 1.2 MB/s eta 0:01:22
   - -------------------------------------- 3.4/101.7 MB 1.2 MB/s eta 0:01:22
   - -------------------------------------- 3.7/101.7 MB 1.2 MB/s eta 0:01:22
   - -------------------------------------- 3.7/101.7 MB 1.2 MB/s eta 0:01:22
   - -------------------------------------- 4.2/101.7 MB 1.1 MB/s eta 0:01:26
   - -------------------------------------- 4.5/101.7 MB 1.2 MB/s eta 0:01:22
   - -------------------------------------- 4.7/101.7 MB 1.2 MB/s eta 0:01:24
   - -------------------------------------- 5.0/101.7 MB 1.2 MB/s eta 0:01:22
   - -------------------------------------- 5.0/101.7 MB 1.2 MB/s eta 0:01:22
   -- ------------------------------------- 5.5/101.7 MB 1.2 MB/s eta 0:01:23
   -- ------------------------------------- 5.8/101.7 MB 1.2 MB/s eta 0:01:21
   -- ------------------------------------- 5.8/101.7 MB 1.2 MB/s eta 0:01:21
   -- ------------------------------------- 6.3/101.7 MB 1.2 MB/s eta 0:01:20
   -- ------------------------------------- 6.6/101.7 MB 1.2 MB/s eta 0:01:21
   -- ------------------------------------- 6.8/101.7 MB 1.2 MB/s eta 0:01:21
   -- ------------------------------------- 7.1/101.7 MB 1.2 MB/s eta 0:01:20
   -- ------------------------------------- 7.3/101.7 MB 1.2 MB/s eta 0:01:20
   -- ------------------------------------- 7.6/101.7 MB 1.2 MB/s eta 0:01:20
   --- ------------------------------------ 7.9/101.7 MB 1.2 MB/s eta 0:01:20
   --- ------------------------------------ 8.1/101.7 MB 1.2 MB/s eta 0:01:18
   --- ------------------------------------ 8.4/101.7 MB 1.2 MB/s eta 0:01:19
   --- ------------------------------------ 8.7/101.7 MB 1.2 MB/s eta 0:01:18
   --- ------------------------------------ 8.9/101.7 MB 1.2 MB/s eta 0:01:18
   --- ------------------------------------ 9.2/101.7 MB 1.2 MB/s eta 0:01:18
   --- ------------------------------------ 9.4/101.7 MB 1.2 MB/s eta 0:01:18
   --- ------------------------------------ 9.4/101.7 MB 1.2 MB/s eta 0:01:18
   --- ------------------------------------ 9.7/101.7 MB 1.2 MB/s eta 0:01:18
   --- ------------------------------------ 10.0/101.7 MB 1.2 MB/s eta 0:01:18
   ---- ----------------------------------- 10.2/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 10.5/101.7 MB 1.2 MB/s eta 0:01:18
   ---- ----------------------------------- 10.7/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 11.0/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 11.0/101.7 MB 1.2 MB/s eta 0:01:17
   ---- ----------------------------------- 11.3/101.7 MB 1.2 MB/s eta 0:01:18
   ---- ----------------------------------- 11.3/101.7 MB 1.2 MB/s eta 0:01:18
   ---- ----------------------------------- 11.5/101.7 MB 1.1 MB/s eta 0:01:19
   ---- ----------------------------------- 11.5/101.7 MB 1.1 MB/s eta 0:01:19
   ---- ----------------------------------- 11.5/101.7 MB 1.1 MB/s eta 0:01:19
   ---- ----------------------------------- 11.5/101.7 MB 1.1 MB/s eta 0:01:19
   ---- ----------------------------------- 11.5/101.7 MB 1.1 MB/s eta 0:01:19
   ---- ----------------------------------- 11.5/101.7 MB 1.1 MB/s eta 0:01:19
   ---- ----------------------------------- 11.8/101.7 MB 1.0 MB/s eta 0:01:27
   ---- ----------------------------------- 11.8/101.7 MB 1.0 MB/s eta 0:01:27
   ---- ----------------------------------- 11.8/101.7 MB 1.0 MB/s eta 0:01:27
   ---- ----------------------------------- 11.8/101.7 MB 1.0 MB/s eta 0:01:27
   ---- ----------------------------------- 11.8/101.7 MB 1.0 MB/s eta 0:01:27
   ---- ---------------------------------- 12.1/101.7 MB 958.1 kB/s eta 0:01:34
   ---- ---------------------------------- 12.1/101.7 MB 958.1 kB/s eta 0:01:34
   ---- ---------------------------------- 12.1/101.7 MB 958.1 kB/s eta 0:01:34
   ---- ---------------------------------- 12.3/101.7 MB 936.6 kB/s eta 0:01:36
   ---- ---------------------------------- 12.6/101.7 MB 942.1 kB/s eta 0:01:35
   ---- ---------------------------------- 12.6/101.7 MB 942.1 kB/s eta 0:01:35
   ---- ---------------------------------- 12.8/101.7 MB 932.1 kB/s eta 0:01:36
   ---- ---------------------------------- 12.8/101.7 MB 932.1 kB/s eta 0:01:36
   ----- --------------------------------- 13.1/101.7 MB 925.8 kB/s eta 0:01:36
   ----- --------------------------------- 13.6/101.7 MB 941.3 kB/s eta 0:01:34
   ----- --------------------------------- 13.6/101.7 MB 941.3 kB/s eta 0:01:34
   ----- --------------------------------- 14.2/101.7 MB 950.0 kB/s eta 0:01:33
   ----- --------------------------------- 14.2/101.7 MB 950.0 kB/s eta 0:01:33
   ----- --------------------------------- 14.2/101.7 MB 950.0 kB/s eta 0:01:33
   ----- --------------------------------- 14.4/101.7 MB 932.1 kB/s eta 0:01:34
   ----- --------------------------------- 14.7/101.7 MB 937.8 kB/s eta 0:01:33
   ----- --------------------------------- 14.9/101.7 MB 941.5 kB/s eta 0:01:33
   ----- --------------------------------- 15.2/101.7 MB 945.9 kB/s eta 0:01:32
   ----- --------------------------------- 15.2/101.7 MB 945.9 kB/s eta 0:01:32
   ------ -------------------------------- 15.7/101.7 MB 950.0 kB/s eta 0:01:31
   ------ -------------------------------- 16.0/101.7 MB 954.2 kB/s eta 0:01:30
   ------ -------------------------------- 16.3/101.7 MB 954.7 kB/s eta 0:01:30
   ------ -------------------------------- 16.5/101.7 MB 961.4 kB/s eta 0:01:29
   ------ -------------------------------- 16.5/101.7 MB 961.4 kB/s eta 0:01:29
   ------ -------------------------------- 16.5/101.7 MB 961.4 kB/s eta 0:01:29
   ------ -------------------------------- 16.8/101.7 MB 936.2 kB/s eta 0:01:31
   ------ -------------------------------- 16.8/101.7 MB 936.2 kB/s eta 0:01:31
   ------ -------------------------------- 16.8/101.7 MB 936.2 kB/s eta 0:01:31
   ------ -------------------------------- 16.8/101.7 MB 936.2 kB/s eta 0:01:31
   ------ -------------------------------- 16.8/101.7 MB 936.2 kB/s eta 0:01:31
   ------ -------------------------------- 17.0/101.7 MB 906.9 kB/s eta 0:01:34
   ------ -------------------------------- 17.0/101.7 MB 906.9 kB/s eta 0:01:34
   ------ -------------------------------- 17.3/101.7 MB 894.6 kB/s eta 0:01:35
   ------ -------------------------------- 17.3/101.7 MB 894.6 kB/s eta 0:01:35
   ------ -------------------------------- 17.3/101.7 MB 894.6 kB/s eta 0:01:35
   ------ -------------------------------- 17.6/101.7 MB 881.6 kB/s eta 0:01:36
   ------ -------------------------------- 17.6/101.7 MB 881.6 kB/s eta 0:01:36
   ------ -------------------------------- 17.8/101.7 MB 870.0 kB/s eta 0:01:37
   ------ -------------------------------- 17.8/101.7 MB 870.0 kB/s eta 0:01:37
   ------ -------------------------------- 17.8/101.7 MB 870.0 kB/s eta 0:01:37
   ------ -------------------------------- 18.1/101.7 MB 861.7 kB/s eta 0:01:38
   ------- ------------------------------- 18.4/101.7 MB 863.9 kB/s eta 0:01:37
   ------- ------------------------------- 18.4/101.7 MB 863.9 kB/s eta 0:01:37
   ------- ------------------------------- 18.6/101.7 MB 859.8 kB/s eta 0:01:37
   ------- ------------------------------- 18.9/101.7 MB 864.4 kB/s eta 0:01:36
   ------- ------------------------------- 19.1/101.7 MB 861.0 kB/s eta 0:01:36
   ------- ------------------------------- 19.1/101.7 MB 861.0 kB/s eta 0:01:36
   ------- ------------------------------- 19.4/101.7 MB 856.5 kB/s eta 0:01:37
   ------- ------------------------------- 19.4/101.7 MB 856.5 kB/s eta 0:01:37
   ------- ------------------------------- 19.4/101.7 MB 856.5 kB/s eta 0:01:37
   ------- ------------------------------- 19.4/101.7 MB 856.5 kB/s eta 0:01:37
   ------- ------------------------------- 19.4/101.7 MB 856.5 kB/s eta 0:01:37
   ------- ------------------------------- 19.4/101.7 MB 856.5 kB/s eta 0:01:37
   ------- ------------------------------- 19.4/101.7 MB 856.5 kB/s eta 0:01:37
   ------- ------------------------------- 19.4/101.7 MB 856.5 kB/s eta 0:01:37
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.7/101.7 MB 811.5 kB/s eta 0:01:42
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 19.9/101.7 MB 684.6 kB/s eta 0:02:00
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.2/101.7 MB 518.2 kB/s eta 0:02:38
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.4/101.7 MB 334.8 kB/s eta 0:04:03
   ------- ------------------------------- 20.7/101.7 MB 289.0 kB/s eta 0:04:41
   ------- ------------------------------- 20.7/101.7 MB 289.0 kB/s eta 0:04:41
   ------- ------------------------------- 20.7/101.7 MB 289.0 kB/s eta 0:04:41
   ------- ------------------------------- 20.7/101.7 MB 289.0 kB/s eta 0:04:41
   ------- ------------------------------- 20.7/101.7 MB 289.0 kB/s eta 0:04:41
   ------- ------------------------------- 20.7/101.7 MB 289.0 kB/s eta 0:04:41
   ------- ------------------------------- 20.7/101.7 MB 289.0 kB/s eta 0:04:41
   ------- ------------------------------- 20.7/101.7 MB 289.0 kB/s eta 0:04:41
   ------- ------------------------------- 20.7/101.7 MB 289.0 kB/s eta 0:04:41
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30
   -------- ------------------------------ 21.0/101.7 MB 244.8 kB/s eta 0:05:30

WARNING: Ignoring invalid distribution ~ip (C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages)

   ----------------------------- --------- 75.8/101.7 MB 244.7 kB/s eta 0:01:46
   ----------------------------- --------- 75.8/101.7 MB 244.7 kB/s eta 0:01:46
   ----------------------------- --------- 76.0/101.7 MB 245.4 kB/s eta 0:01:45
   ----------------------------- --------- 76.0/101.7 MB 245.4 kB/s eta 0:01:45
   ----------------------------- --------- 76.3/101.7 MB 248.8 kB/s eta 0:01:43
   ----------------------------- --------- 76.5/101.7 MB 256.2 kB/s eta 0:01:39
   ----------------------------- --------- 76.5/101.7 MB 256.2 kB/s eta 0:01:39
   ----------------------------- --------- 76.8/101.7 MB 257.2 kB/s eta 0:01:37
   ----------------------------- --------- 77.1/101.7 MB 262.7 kB/s eta 0:01:34
   ----------------------------- --------- 77.1/101.7 MB 262.7 kB/s eta 0:01:34
   ----------------------------- --------- 77.1/101.7 MB 262.7 kB/s eta 0:01:34
   ----------------------------- --------- 77.3/101.7 MB 269.0 kB/s eta 0:01:31
   ----------------------------- --------- 77.3/101.7 MB 269.0 kB/s eta 0:01:31
   ----------------------------- --------- 77.3/101.7 MB 269.0 kB/s eta 0:01:31
   ----------------------------- --------- 77.3/101.7 MB 269.0 kB/s eta 0:01:31
   ----------------------------- --------- 77.3/101.7 MB 269.0 kB/s eta 0:01:31
   ----------------------------- --------- 77.3/101.7 MB 269.0 kB/s eta 0:01:31
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.6/101.7 MB 300.8 kB/s eta 0:01:21
   ----------------------------- --------- 77.9/101.7 MB 286.5 kB/s eta 0:01:24
   ----------------------------- --------- 77.9/101.7 MB 286.5 kB/s eta 0:01:24
   ----------------------------- --------- 77.9/101.7 MB 286.5 kB/s eta 0:01:24
   ----------------------------- --------- 77.9/101.7 MB 286.5 kB/s eta 0:01:24
   ----------------------------- --------- 78.1/101.7 MB 286.6 kB/s eta 0:01:23
   ----------------------------- --------- 78.1/101.7 MB 286.6 kB/s eta 0:01:23
   ----------------------------- --------- 78.1/101.7 MB 286.6 kB/s eta 0:01:23
   ----------------------------- --------- 78.1/101.7 MB 286.6 kB/s eta 0:01:23
   ------------------------------ -------- 78.4/101.7 MB 336.6 kB/s eta 0:01:10
   ------------------------------ -------- 78.4/101.7 MB 336.6 kB/s eta 0:01:10
   ------------------------------ -------- 78.4/101.7 MB 336.6 kB/s eta 0:01:10
   ------------------------------ -------- 78.4/101.7 MB 336.6 kB/s eta 0:01:10
   ------------------------------ -------- 78.6/101.7 MB 336.1 kB/s eta 0:01:09
   ------------------------------ -------- 78.6/101.7 MB 336.1 kB/s eta 0:01:09
   ------------------------------ -------- 78.9/101.7 MB 339.7 kB/s eta 0:01:08
   ------------------------------ -------- 79.2/101.7 MB 348.3 kB/s eta 0:01:05
   ------------------------------ -------- 79.2/101.7 MB 348.3 kB/s eta 0:01:05
   ------------------------------ -------- 79.2/101.7 MB 348.3 kB/s eta 0:01:05
   ------------------------------ -------- 79.4/101.7 MB 349.9 kB/s eta 0:01:04
   ------------------------------ -------- 79.4/101.7 MB 349.9 kB/s eta 0:01:04
   ------------------------------ -------- 79.7/101.7 MB 352.5 kB/s eta 0:01:03
   ------------------------------ -------- 79.7/101.7 MB 352.5 kB/s eta 0:01:03
   ------------------------------ -------- 79.7/101.7 MB 352.5 kB/s eta 0:01:03
   ------------------------------ -------- 80.0/101.7 MB 356.0 kB/s eta 0:01:02
   ------------------------------ -------- 80.0/101.7 MB 356.0 kB/s eta 0:01:02
   ------------------------------ -------- 80.2/101.7 MB 359.7 kB/s eta 0:01:00
   ------------------------------ -------- 80.5/101.7 MB 364.3 kB/s eta 0:00:59
   ------------------------------ -------- 80.5/101.7 MB 364.3 kB/s eta 0:00:59
   ------------------------------ -------- 80.7/101.7 MB 369.2 kB/s eta 0:00:57
   ------------------------------ -------- 80.7/101.7 MB 369.2 kB/s eta 0:00:57
   ------------------------------- ------- 81.0/101.7 MB 371.1 kB/s eta 0:00:56
   ------------------------------- ------- 81.0/101.7 MB 371.1 kB/s eta 0:00:56
   ------------------------------- ------- 81.3/101.7 MB 376.3 kB/s eta 0:00:55
   ------------------------------- ------- 81.8/101.7 MB 443.9 kB/s eta 0:00:45
   ------------------------------- ------- 81.8/101.7 MB 443.9 kB/s eta 0:00:45
   ------------------------------- ------- 81.8/101.7 MB 443.9 kB/s eta 0:00:45
   ------------------------------- ------- 82.1/101.7 MB 445.1 kB/s eta 0:00:45
   ------------------------------- ------- 82.1/101.7 MB 445.1 kB/s eta 0:00:45
   ------------------------------- ------- 82.1/101.7 MB 445.1 kB/s eta 0:00:45
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.3/101.7 MB 441.8 kB/s eta 0:00:44
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.6/101.7 MB 418.3 kB/s eta 0:00:46
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 82.8/101.7 MB 386.1 kB/s eta 0:00:49
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.1/101.7 MB 276.8 kB/s eta 0:01:08
   ------------------------------- ------- 83.4/101.7 MB 247.9 kB/s eta 0:01:14
   ------------------------------- ------- 83.4/101.7 MB 247.9 kB/s eta 0:01:14
   ------------------------------- ------- 83.4/101.7 MB 247.9 kB/s eta 0:01:14
   ------------------------------- ------- 83.4/101.7 MB 247.9 kB/s eta 0:01:14
   ------------------------------- ------- 83.4/101.7 MB 247.9 kB/s eta 0:01:14
   ------------------------------- ------- 83.4/101.7 MB 247.9 kB/s eta 0:01:14
   -------------------------------- ------ 83.6/101.7 MB 229.0 kB/s eta 0:01:19
   -------------------------------- ------ 83.6/101.7 MB 229.0 kB/s eta 0:01:19
   -------------------------------- ------ 83.6/101.7 MB 229.0 kB/s eta 0:01:19
   -------------------------------- ------ 83.6/101.7 MB 229.0 kB/s eta 0:01:19
   -------------------------------- ------ 83.9/101.7 MB 220.1 kB/s eta 0:01:21
   -------------------------------- ------ 83.9/101.7 MB 220.1 kB/s eta 0:01:21
   -------------------------------- ------ 83.9/101.7 MB 220.1 kB/s eta 0:01:21
   -------------------------------- ------ 84.1/101.7 MB 223.8 kB/s eta 0:01:19
   -------------------------------- ------ 84.1/101.7 MB 223.8 kB/s eta 0:01:19
   -------------------------------- ------ 84.1/101.7 MB 223.8 kB/s eta 0:01:19
   -------------------------------- ------ 84.4/101.7 MB 227.5 kB/s eta 0:01:16
   -------------------------------- ------ 84.4/101.7 MB 227.5 kB/s eta 0:01:16
   -------------------------------- ------ 84.4/101.7 MB 227.5 kB/s eta 0:01:16
   -------------------------------- ------ 84.7/101.7 MB 241.3 kB/s eta 0:01:11
   -------------------------------- ------ 84.7/101.7 MB 241.3 kB/s eta 0:01:11
   -------------------------------- ------ 84.9/101.7 MB 246.7 kB/s eta 0:01:08
   -------------------------------- ------ 85.2/101.7 MB 252.6 kB/s eta 0:01:06
   -------------------------------- ------ 85.2/101.7 MB 252.6 kB/s eta 0:01:06
   -------------------------------- ------ 85.2/101.7 MB 252.6 kB/s eta 0:01:06
   -------------------------------- ------ 85.5/101.7 MB 256.3 kB/s eta 0:01:04
   -------------------------------- ------ 85.5/101.7 MB 256.3 kB/s eta 0:01:04
   -------------------------------- ------ 85.7/101.7 MB 260.9 kB/s eta 0:01:02
   -------------------------------- ------ 85.7/101.7 MB 260.9 kB/s eta 0:01:02
   -------------------------------- ------ 86.0/101.7 MB 265.6 kB/s eta 0:01:00
   -------------------------------- ------ 86.0/101.7 MB 265.6 kB/s eta 0:01:00
   -------------------------------- ------ 86.0/101.7 MB 265.6 kB/s eta 0:01:00
   -------------------------------- ------ 86.0/101.7 MB 265.6 kB/s eta 0:01:00
   -------------------------------- ------ 86.0/101.7 MB 265.6 kB/s eta 0:01:00
   --------------------------------- ----- 86.2/101.7 MB 264.1 kB/s eta 0:00:59
   --------------------------------- ----- 86.2/101.7 MB 264.1 kB/s eta 0:00:59
   --------------------------------- ----- 86.2/101.7 MB 264.1 kB/s eta 0:00:59
   --------------------------------- ----- 86.2/101.7 MB 264.1 kB/s eta 0:00:59
   --------------------------------- ----- 86.2/101.7 MB 264.1 kB/s eta 0:00:59
   --------------------------------- ----- 86.2/101.7 MB 264.1 kB/s eta 0:00:59
   --------------------------------- ----- 86.2/101.7 MB 264.1 kB/s eta 0:00:59
   --------------------------------- ----- 86.2/101.7 MB 264.1 kB/s eta 0:00:59
   --------------------------------- ----- 86.2/101.7 MB 264.1 kB/s eta 0:00:59
   --------------------------------- ----- 86.5/101.7 MB 239.0 kB/s eta 0:01:04
   --------------------------------- ----- 86.5/101.7 MB 239.0 kB/s eta 0:01:04
   --------------------------------- ----- 86.5/101.7 MB 239.0 kB/s eta 0:01:04
   --------------------------------- ----- 86.5/101.7 MB 239.0 kB/s eta 0:01:04
   --------------------------------- ----- 86.8/101.7 MB 236.1 kB/s eta 0:01:04
   --------------------------------- ----- 86.8/101.7 MB 236.1 kB/s eta 0:01:04
   --------------------------------- ----- 86.8/101.7 MB 236.1 kB/s eta 0:01:04
   --------------------------------- ----- 86.8/101.7 MB 236.1 kB/s eta 0:01:04
   --------------------------------- ----- 86.8/101.7 MB 236.1 kB/s eta 0:01:04
   --------------------------------- ----- 87.0/101.7 MB 219.7 kB/s eta 0:01:07
   --------------------------------- ----- 87.0/101.7 MB 219.7 kB/s eta 0:01:07
   --------------------------------- ----- 87.0/101.7 MB 219.7 kB/s eta 0:01:07
   --------------------------------- ----- 87.3/101.7 MB 218.7 kB/s eta 0:01:06
   --------------------------------- ----- 87.6/101.7 MB 219.9 kB/s eta 0:01:05
   --------------------------------- ----- 87.6/101.7 MB 219.9 kB/s eta 0:01:05
   --------------------------------- ----- 87.6/101.7 MB 219.9 kB/s eta 0:01:05
   --------------------------------- ----- 87.6/101.7 MB 219.9 kB/s eta 0:01:05
   --------------------------------- ----- 87.8/101.7 MB 201.4 kB/s eta 0:01:09
   --------------------------------- ----- 88.1/101.7 MB 202.6 kB/s eta 0:01:08
   --------------------------------- ----- 88.3/101.7 MB 206.3 kB/s eta 0:01:05
   --------------------------------- ----- 88.3/101.7 MB 206.3 kB/s eta 0:01:05
   --------------------------------- ----- 88.3/101.7 MB 206.3 kB/s eta 0:01:05
   --------------------------------- ----- 88.3/101.7 MB 206.3 kB/s eta 0:01:05
   --------------------------------- ----- 88.6/101.7 MB 209.9 kB/s eta 0:01:03
   --------------------------------- ----- 88.6/101.7 MB 209.9 kB/s eta 0:01:03
   --------------------------------- ----- 88.6/101.7 MB 209.9 kB/s eta 0:01:03
   ---------------------------------- ---- 88.9/101.7 MB 226.3 kB/s eta 0:00:57
   ---------------------------------- ---- 88.9/101.7 MB 226.3 kB/s eta 0:00:57
   ---------------------------------- ---- 89.1/101.7 MB 232.1 kB/s eta 0:00:55
   ---------------------------------- ---- 89.1/101.7 MB 232.1 kB/s eta 0:00:55
   ---------------------------------- ---- 89.1/101.7 MB 232.1 kB/s eta 0:00:55
   ---------------------------------- ---- 89.1/101.7 MB 232.1 kB/s eta 0:00:55
   ---------------------------------- ---- 89.1/101.7 MB 232.1 kB/s eta 0:00:55
   ---------------------------------- ---- 89.1/101.7 MB 232.1 kB/s eta 0:00:55
   ---------------------------------- ---- 89.4/101.7 MB 232.0 kB/s eta 0:00:53
   ---------------------------------- ---- 89.4/101.7 MB 232.0 kB/s eta 0:00:53
   ---------------------------------- ---- 89.4/101.7 MB 232.0 kB/s eta 0:00:53
   ---------------------------------- ---- 89.4/101.7 MB 232.0 kB/s eta 0:00:53
   ---------------------------------- ---- 89.4/101.7 MB 232.0 kB/s eta 0:00:53
   ---------------------------------- ---- 89.4/101.7 MB 232.0 kB/s eta 0:00:53
   ---------------------------------- ---- 89.4/101.7 MB 232.0 kB/s eta 0:00:53
   ---------------------------------- ---- 89.7/101.7 MB 243.3 kB/s eta 0:00:50
   ---------------------------------- ---- 89.7/101.7 MB 243.3 kB/s eta 0:00:50
   ---------------------------------- ---- 89.7/101.7 MB 243.3 kB/s eta 0:00:50
   ---------------------------------- ---- 89.7/101.7 MB 243.3 kB/s eta 0:00:50
   ---------------------------------- ---- 89.7/101.7 MB 243.3 kB/s eta 0:00:50
   ---------------------------------- ---- 89.9/101.7 MB 243.3 kB/s eta 0:00:49
   ---------------------------------- ---- 89.9/101.7 MB 243.3 kB/s eta 0:00:49
   ---------------------------------- ---- 89.9/101.7 MB 243.3 kB/s eta 0:00:49
   ---------------------------------- ---- 90.2/101.7 MB 247.0 kB/s eta 0:00:47
   ---------------------------------- ---- 90.2/101.7 MB 247.0 kB/s eta 0:00:47
   ---------------------------------- ---- 90.2/101.7 MB 247.0 kB/s eta 0:00:47
   ---------------------------------- ---- 90.2/101.7 MB 247.0 kB/s eta 0:00:47
   ---------------------------------- ---- 90.4/101.7 MB 312.1 kB/s eta 0:00:37
   ---------------------------------- ---- 90.7/101.7 MB 320.1 kB/s eta 0:00:35
   ---------------------------------- ---- 90.7/101.7 MB 320.1 kB/s eta 0:00:35
   ---------------------------------- ---- 90.7/101.7 MB 320.1 kB/s eta 0:00:35
   ---------------------------------- ---- 91.0/101.7 MB 323.0 kB/s eta 0:00:34
   ---------------------------------- ---- 91.0/101.7 MB 323.0 kB/s eta 0:00:34
   ---------------------------------- ---- 91.0/101.7 MB 323.0 kB/s eta 0:00:34
   ---------------------------------- ---- 91.2/101.7 MB 323.8 kB/s eta 0:00:33
   ---------------------------------- ---- 91.2/101.7 MB 323.8 kB/s eta 0:00:33
   ---------------------------------- ---- 91.2/101.7 MB 323.8 kB/s eta 0:00:33
   ---------------------------------- ---- 91.2/101.7 MB 323.8 kB/s eta 0:00:33
   ----------------------------------- --- 91.5/101.7 MB 324.6 kB/s eta 0:00:32
   ----------------------------------- --- 91.5/101.7 MB 324.6 kB/s eta 0:00:32

In [7]:
!pip install xgboost

WARNING: Ignoring invalid distribution ~ip (C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages)

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages (3.2.0)
Requirement already satisfied: numpy in C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages (from xgboost) (1.16.2)

In [8]:
import sys
!{sys.executable} -m pip install xgboost

Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.15.3)
Using cached xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
from xgboost import XGBClassifier

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [4]:
import numpy as np
import pandas as pd

In [6]:
import pandas as pd

df = pd.read_csv(r'C:\Users\ADMIN\OneDrive\Desktop\ml-libraries-and-frame-work\data.csv')

df.head()

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,liked
0,0.803,0.6240,7,-6.764,0,0.0477,0.451,0.000734,0.1000,0.6280,95.968,304524,4,0
1,0.762,0.7030,10,-7.951,0,0.3060,0.206,0.000000,0.0912,0.5190,151.329,247178,4,1
2,0.261,0.0149,1,-27.528,1,0.0419,0.992,0.897000,0.1020,0.0382,75.296,286987,4,0
3,0.722,0.7360,3,-6.994,0,0.0585,0.431,0.000001,0.1230,0.5820,89.860,208920,4,1
4,0.787,0.5720,1,-7.516,1,0.2220,0.145,0.000000,0.0753,0.6470,155.117,179413,4,1

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from xgboost import XGBClassifier

In [ ]:
df.head()
df.head(columns)

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,liked
0,0.803,0.6240,7,-6.764,0,0.0477,0.451,0.000734,0.1000,0.6280,95.968,304524,4,0
1,0.762,0.7030,10,-7.951,0,0.3060,0.206,0.000000,0.0912,0.5190,151.329,247178,4,1
2,0.261,0.0149,1,-27.528,1,0.0419,0.992,0.897000,0.1020,0.0382,75.296,286987,4,0
3,0.722,0.7360,3,-6.994,0,0.0585,0.431,0.000001,0.1230,0.5820,89.860,208920,4,1
4,0.787,0.5720,1,-7.516,1,0.2220,0.145,0.000000,0.0753,0.6470,155.117,179413,4,1

In [10]:
df.head()

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,liked
0,0.803,0.6240,7,-6.764,0,0.0477,0.451,0.000734,0.1000,0.6280,95.968,304524,4,0
1,0.762,0.7030,10,-7.951,0,0.3060,0.206,0.000000,0.0912,0.5190,151.329,247178,4,1
2,0.261,0.0149,1,-27.528,1,0.0419,0.992,0.897000,0.1020,0.0382,75.296,286987,4,0
3,0.722,0.7360,3,-6.994,0,0.0585,0.431,0.000001,0.1230,0.5820,89.860,208920,4,1
4,0.787,0.5720,1,-7.516,1,0.2220,0.145,0.000000,0.0753,0.6470,155.117,179413,4,1

In [11]:
df.columns

Index(['danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms', 'time_signature', 'liked'],
      dtype='object')

In [12]:
X = df.drop('liked', axis=1)
y = df['liked']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y   # keeps class balance
)

In [13]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=6,
    random_state=42
)

rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

print("Random Forest Accuracy:",
      accuracy_score(y_test, rf_pred))

Random Forest Accuracy: 0.9661016949152542

In [14]:
xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)

print("XGBoost Accuracy:",
      accuracy_score(y_test, xgb_pred))

XGBoost Accuracy: 0.9152542372881356

In [15]:
voting = VotingClassifier(
    estimators=[
        ('rf', rf),
        ('xgb', xgb)
    ],
    voting='soft'
)

voting.fit(X_train, y_train)
voting_pred = voting.predict(X_test)

print("Voting Ensemble Accuracy:",
      accuracy_score(y_test, voting_pred))

Voting Ensemble Accuracy: 0.9491525423728814